### ISSUE TITLE
In MvcFragment EventBusC2V is being used to post V2V events.

### ISSUE THREAD

**Issue by venkatesh3007** [kejunxia/AndroidMvc#29]
protected void postEventV2V(BaseEventV2V event) {
          AndroidMvc.getEventBusC2V().post(event);
    }

In the documentation you have specified that there are three separate event buses for different types of events then why is postEventV2V posting on C2V Event bus.

**Comment by kejunxia** [comment]
Hi Vanketash, thanks for reporting this. It looks like a bug. I will fix it.
