### ISSUE TITLE
Different Instances of Manager is getting created when used navigate() with Forwarder

### ISSUE THREAD

**Issue by nikhil19patil** [kejunxia/AndroidMvc#48]
I have used navigate method from NavigationManager to with Forwader as follows

Forwarder forwarder = new Forwarder();
forwarder.clearTo(locationId2);
navigationManager.navigate(sender).to(locationId1, forwarder);

here locationId1 and locationId1 are two fragments

I have used common manager inside controllers of these fragments. I have set model of manager inside controller of locationId1 fragment. then I used navigate method as above to navigate from locationId1 to locationId2. Now, when i try to access model of manager from controller of locationId2 Fragment then I am getting blank model.

I have checked in debug mode then I found that i am getting different instances of manager in both controllers.

**Comment by kejunxia** [comment]
What's the navigation stack before navigation from locationId1? I am a bit confused about the your app state before navigation. From what I read I assume something like this
...->locationId2->locationId3 : current
Then you want to navigate to locationId1 and clear the history up to locationId2 so it becomes below after navigation
...->locationId2->locationId1

Am I right?

If the shared manager are injected by @Inject in both controller of locationId1and locationId2. It should be carried over to the next controller on navigation. Another way to preset the state/model of the next controller is do this

        navigationManager.navigate(sender).with(NextScreenController.class, new Preparer<CounterDetailController>() {
            @Override
            public void prepare(NextScreenController controller) {
                //Set the controller of the next screen before navigation starts. 
                //The controller is prepared and will be injected into the next screen
               
            }
        });

**Comment by venkatesh3007** [comment]
> What's the navigation stack before navigation from locationId1? I am a bit confused about the your app state before navigation. From what I read I assume something like this
...->locationId2->locationId3 : current
Then you want to navigate to locationId1 and clear the history up to locationId2 so it becomes below after navigation
...->locationId2->locationId1

Yes, you are right.

> If the shared manager are injected by @Inject in both controller of locationId1 and locationId2. It should be carried over to the next controller on navigation.

A new instance is getting created for the shared manager in the next controller on navigation despite  being injected in both the controllers by @Inject.

**Comment by kejunxia** [comment]
Which version you are on? I will have a check.

**Comment by venkatesh3007** [comment]
It is 2.3.0.

**Comment by kejunxia** [comment]
I updated the sample(simple) in this branch https://github.com/kejunxia/AndroidMvc/tree/UpdateSampleForVersion2.3/samples/simple

I used a shared manager countManager across multiple controllers and their enclosing fragments. It works fine in the code. 

Could you have a look see if there is any difference causing the issue you are encountering?

**Comment by venkatesh3007** [comment]
@kejunxia, sure. We will check it and let you know.

**Comment by nikhil19patil** [comment]
@kejunxia I have checked your example.
But my requirement is as follows
I have three fragments A,  B and C
I am navigating like this :  A -> B -> C
But when i press back button on Fragment C then it should directly come to Fragment A by clearing Fragment B from backstack
And meanwhile i am using same manager in all of these fragments controllers. 
So the problem is when i use 

        Forwarder forwarder = new Forwarder();
        forwarder.clearTo("LocationC");
        navigationManager.navigate(sender).to("LocationB", forwarder)

for navigating from Fragment B to Fragment C then new instances of manager are getting created.

so would you please demonstrate your example that how can i use following method for clearing some fragment from backstack

  ```
 /**
     * Navigate to the next location.
     * @param locationId The id of the location navigating to.
     * @param forwarder The configuration by {@link Forwarder} of the forward navigation.
     */
    public void to(String locationId, @NotNull Forwarder forwarder) {
        doNavigateTo(locationId, forwarder);
        go();
    }
```
 That would be very helpful.

**Comment by kejunxia** [comment]
I created a new branch.

In the branch I added an new fragment called FragmentInterim and corresponding controller.

in ControllerInterim.goToPageB()
navigationManager.navigate(this).to("LocationB");

in ControllerB.navigateBack(Object sender)
navigationManager.navigate(sender).back("LocationA");

Can you have a check if that's what you are after?

**Comment by nikhil19patil** [comment]
```
in ControllerB.navigateBack(Object sender)
navigationManager.navigate(sender).back("LocationA");
```

working well.
Thanks :+1:
