### ISSUE TITLE
Help needed in understanding flow of test cases to test controllers

### ISSUE THREAD

**Issue by poojadeshpande91** [kejunxia/AndroidMvc#56]
Having gone through some test cases you have given, I could not get the flow of it or any documentation.

**Comment by kejunxia** [comment]
Let me know if this helps
https://kejunxia.github.io/AndroidMvc/#easy-unit-test

**Comment by poojadeshpande91** [comment]
I went through this, can you tell me where you are writing these test cases and how are you executing them ? A little more explanation will be very helpful

**Comment by kejunxia** [comment]
Also see details in the sample code. https://github.com/kejunxia/AndroidMvc/tree/master/samples/simple-mvp

Test cases are written in core module under core/src/test, see
https://github.com/kejunxia/AndroidMvc/tree/master/samples/simple-mvp/core/src/test/java/com/shipdream/lib/android/mvc/samples/simple/mvp/controller/internal

They are basic JUnit test cases. You can run them through Android studio by right clicking the test folder and you will see the test runs.

Or through your gradle console task: gradlew test

You can try add code below into your app module's build.gradle file out of the android block to enforce your controllers tests have to be passed when compiling your Android app

android.applicationVariants.all {
    variant -> variant.assemble.dependsOn(":core:test")
}

**Comment by poojadeshpande91** [comment]
Thank you this helped
