### ISSUE TITLE
How i can navigate to a spacific fragment when user click on notification while application in background

### ISSUE THREAD

**Issue by IbrahimDisouki** [kejunxia/AndroidMvc#68]
Hello kejunxia,
My application is receiving a push notifications from server while my application is in background and i suppose to open the target fragment when user click on the notification. How i can do this using your amazing library ?

**Comment by kejunxia** [comment]
Hi ibrahim,

What I did was to use a application wide controller say AppController to
manage intent routed from notification. 2 scenarios below,
1. When app is present when notifications come, parse the intent and
broadcast it as a POJO object to other controllers. Or directly reference
the controller to deal with the intent. For example, when a message comes,
in AppController, I "use" ChatControlller and invoke
chatControlller.showMessage(ParsedIntent)
2. When the app is not present, save the parsed intent somewhere e.g.
Preferences and in the app lifecycle check if there are pending intent
saved and handle it the app is brought back.

Hope it helps.

Regards,
Kejun

**Comment by IbrahimDisouki** [comment]
Hi Kejun,
Thanks man it helps me alot.
